In [1]:
import pandas as pd
from load_datasets import split_train_evaluate

### Get the training and test set

In [2]:
train_input = pd.read_csv(r'..\processed_data\X_train.csv')
train_input.head()

,LotFrontage,LotArea,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,...,MoSold_11,MoSold_12,MoSold_2,MoSold_3,MoSold_4,MoSold_5,MoSold_6,MoSold_7,MoSold_8,MoSold_9
0,-0.229372,-0.207142,1.050994,0.878668,0.511418,0.575425,-0.288653,-0.944591,-0.459303,-0.793434,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.451936,-0.091886,0.156734,-0.429577,-0.574410,1.171992,-0.288653,-0.641228,0.466465,0.257140,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,-0.093110,0.073480,0.984752,0.830215,0.323060,0.092907,-0.288653,-0.301643,-0.313369,-0.627826,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,-0.456474,-0.096897,-1.863632,-0.720298,-0.574410,-0.499274,-0.288653,-0.061670,-0.687324,-0.521734,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.633618,0.375148,0.951632,0.733308,1.364570,0.463568,-0.288653,-0.174865,0.199680,-0.045611,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
print(train_input.shape)

(1460, 441)

In [4]:
X_test = pd.read_csv(r'..\processed_data\X_test.csv')

In [5]:
train_target = pd.read_csv(r'..\processed_data\y_train.csv')
train_target.head()

   SalePrice
0     208500
1     181500
2     223500
3     140000
4     250000

### Model Training

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
model = LinearRegression().fit(train_input, train_target)

In [13]:
model, train_loss, val_loss = split_train_evaluate(model, train_input, train_target)

Training Loss: 0.1000726109669687
Validation Loss: 0.09995979743191818

In [9]:
X_test

,LotFrontage,LotArea,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,...,MoSold_11,MoSold_12,MoSold_2,MoSold_3,MoSold_4,MoSold_5,MoSold_6,MoSold_7,MoSold_8,MoSold_9
0,0.451936,0.110763,-0.340077,-1.156380,-0.574410,0.053428,0.604293,-0.672923,-0.400017,-0.689929,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.497357,0.375850,-0.439440,-1.301740,0.023903,1.051363,-0.288653,-0.365032,0.619239,0.430511,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,0.179413,0.332053,0.852269,0.636400,-0.574410,0.761852,-0.288653,-0.974021,-0.295127,-0.607125,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.361095,-0.054002,0.885390,0.636400,-0.463612,0.347326,-0.288653,-0.550672,-0.299687,-0.612300,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,-1.228623,-0.552407,0.686666,0.345679,-0.574410,-0.396190,-0.288653,1.018211,0.507509,0.303718,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,-2.227875,-0.859988,-0.041991,-0.720298,-0.574410,-0.973018,-0.288653,-0.048086,-1.166169,-1.595596,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
1455,-2.227875,-0.864197,-0.041991,-0.720298,-0.574410,-0.420316,-0.288653,-0.618589,-1.166169,-1.595596,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1456,4.085578,0.950423,-0.373198,0.539493,-0.574410,1.711535,-0.288653,-1.284176,0.379817,0.158811,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1457,-0.365633,-0.007600,0.686666,0.345679,-0.574410,-0.233889,-0.288653,0.017567,-0.331610,-0.498445,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1458,0.179413,-0.089180,0.719786,0.442586,-0.053656,0.689474,-0.288653,-0.745367,-0.140072,-0.431167,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
test_preds = model.predict(X_test)
test_preds

array([[115979.80930904],
       [163936.14677862],
       [193994.45472942],
       ...,
       [175140.6462526 ],
       [118477.02198804],
       [219772.19224476]], shape=(1459, 1))

In [11]:
sub_df = pd.read_csv(r'..\sample_submission.csv')
sub_df['SalePrice'] = test_preds
sub_df

        Id      SalePrice
0     1461  115979.809309
1     1462  163936.146779
2     1463  193994.454729
3     1464  195151.897046
4     1465  204497.771362
...    ...            ...
1454  2915   87725.535658
1455  2916   75890.626822
1456  2917  175140.646253
1457  2918  118477.021988
1458  2919  219772.192245

[1459 rows x 2 columns]

In [12]:
sub_df.to_csv(r'..\submissions\lin_reg_mod_sub.csv', index=None)