In [13]:
from load_datasets import load_train_val_test_sets

In [ ]:
X_train, X_test, train_target = load_train_val_test_sets()

In [3]:
X_train.head()

,LotFrontage,LotArea,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,BsmtUnfSF,TotalBsmtSF,1stFlrSF,...,MoSold_11,MoSold_12,MoSold_2,MoSold_3,MoSold_4,MoSold_5,MoSold_6,MoSold_7,MoSold_8,MoSold_9
0,-0.217638,-0.203120,1.042546,0.879097,0.491996,0.573789,-0.284258,-0.944854,-0.457697,-0.791817,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.456955,-0.092266,0.154431,-0.428693,-0.571052,1.166122,-0.284258,-0.644593,0.460728,0.256468,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,-0.082720,0.066786,0.976760,0.830660,0.307590,0.094695,-0.284258,-0.308480,-0.312920,-0.626570,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,-0.442503,-0.097085,-1.852051,-0.719313,-0.571052,-0.493283,-0.284258,-0.070960,-0.683910,-0.520709,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.636847,0.356934,0.943867,0.733787,1.327248,0.462726,-0.284258,-0.182997,0.196059,-0.045624,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

Training the model using Ridge

In [4]:
from sklearn.linear_model import Ridge

In [5]:
from sklearn.metrics import root_mean_squared_error

In [8]:
import pandas as pd

In [ ]:
def alg_test(alg, alpha_params):
  train_loss_l = []
  val_loss_l = []

  for a in alpha_params:
    mod = alg(alpha=a).fit(X_train, train_target)
    train_preds = mod.predict(X_train)
    train_loss = root_mean_squared_error(train_target, train_preds)
    train_loss_l.append(train_loss)
    val_preds = mod.predict(X_val)
    val_loss = root_mean_squared_error(val_target, val_preds)
    val_loss_l.append(val_loss)

  analy_df = pd.DataFrame({'alpha': alpha_params, 'Training Loss': train_loss_l, 'Validation Loss': val_loss_l})
  return analy_df

In [47]:
# Use Ridge regression
r_alpha_params = [0.01, 0.1, 1, 10, 100]
r_mod_analy_df = alg_test(Ridge, r_alpha_params)
r_mod_analy_df

    alpha  Training Loss  Validation Loss
0    0.01   18528.699992     25435.553582
1    0.10   18695.839362     25607.519086
2    1.00   20566.232446     25746.553245
3   10.00   24122.828145     25026.573860
4  100.00   29113.226178     27158.372010

With alpha set to 10, the model performs better

Train model using Lasso

In [18]:
from sklearn.linear_model import Lasso

In [48]:
l_alpha_params = [0.1, 10, 40, 80, 100, 150, 200]
l_mod_analy_df = alg_test(Lasso, l_alpha_params)
l_mod_analy_df

d:\Documents\Coding Prac\ML Projects\Predicting House Prices\.venv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.911747e+11, tolerance: 8.079e+08
  model = cd_fast.enet_coordinate_descent(
d:\Documents\Coding Prac\ML Projects\Predicting House Prices\.venv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.091351e+09, tolerance: 8.079e+08
  model = cd_fast.enet_coordinate_descent(
d:\Documents\Coding Prac\ML Projects\Predicting House Prices\.venv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.645556e+09, tolerance: 8.079e+08
  model = cd_fast.enet_coordinate_descent(

   alpha  Training Loss  Validation Loss
0    0.1   18525.945839     25563.800681
1   10.0   18853.805437     24130.981264
2   40.0   20028.526693     23711.621365
3   80.0   21267.972075     23948.005792
4  100.0   21845.576321     24135.227185
5  150.0   23241.343378     24824.504470
6  200.0   24823.048145     25552.383582

At 40 the model performs better

Train model using Elastic Net

In [49]:
from sklearn.linear_model import ElasticNet

In [72]:
alphas = [0.01, 0.1, 1, 10, 100]
l1_ratios = [0.1, 0.3, 0.5, 0.7, 0.9]
t_loss = []
v_loss = []
al = []
l1 = []

for a in alphas:
  for l in l1_ratios:
    mod = ElasticNet(alpha=a, l1_ratio=l).fit(X_train, train_target)
    target_preds = mod.predict(X_train)
    train_loss = root_mean_squared_error(train_target, target_preds)
    val_loss = root_mean_squared_error(val_target, mod.predict(X_val))

    al.append(a)
    l1.append(l)
    t_loss.append(train_loss)
    v_loss.append(val_loss)

print(al)
print(l1)

el_n_df = pd.DataFrame({
  'alpha': al, 
  'l1_ratio': l1, 
  'training_loss': t_loss,
  'validation_loss': v_loss
})

el_n_df

d:\Documents\Coding Prac\ML Projects\Predicting House Prices\.venv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.275594e+09, tolerance: 8.079e+08
  model = cd_fast.enet_coordinate_descent(
d:\Documents\Coding Prac\ML Projects\Predicting House Prices\.venv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.383334e+11, tolerance: 8.079e+08
  model = cd_fast.enet_coordinate_descent(
d:\Documents\Coding Prac\ML Projects\Predicting House Prices\.venv\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:840: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.254964e+11, tolerance: 8.079e+08
  model = cd_fast.enet_coordinate_descent(

[0.01, 0.01, 0.01, 0.01, 0.01, 0.1, 0.1, 0.1, 0.1, 0.1, 1, 1, 1, 1, 1, 10, 10, 10, 10, 10, 100, 100, 100, 100, 100]
[0.1, 0.3, 0.5, 0.7, 0.9, 0.1, 0.3, 0.5, 0.7, 0.9, 0.1, 0.3, 0.5, 0.7, 0.9, 0.1, 0.3, 0.5, 0.7, 0.9, 0.1, 0.3, 0.5, 0.7, 0.9]

     alpha  l1_ratio  training_loss  validation_loss
0     0.01       0.1   24373.238964     25035.364973
1     0.01       0.3   23943.705898     25029.444974
2     0.01       0.5   23389.192573     25083.866911
3     0.01       0.7   22576.862749     25258.860952
4     0.01       0.9   20916.210224     25684.298208
5     0.10       0.1   29515.464242     27431.753106
6     0.10       0.3   28826.313421     26969.485194
7     0.10       0.5   27950.510860     26425.109057
8     0.10       0.7   26736.996609     25762.981535
9     0.10       0.9   24560.002417     25051.337786
10    1.00       0.1   36581.388396     34532.176981
11    1.00       0.3   35704.942697     33391.252418
12    1.00       0.5   34616.781613     32058.013200
13    1.00       0.7   33052.749074     30362.639195
14    1.00       0.9   29819.720912     27644.062277
15   10.00       0.1   54032.616835     55206.247232
16   10.00       0.3   51061.840440     52050.946775
17   10.00       0.5   47398.362280     48024.934560
18   10.00       0.7   42862.088892     42720.398243
19   10.00       0.9   36992.523812     35071.478140
20  100.00       0.1   74664.963141     75844.588858
21  100.00       0.3   73494.995287     74707.390007
22  100.00       0.5   71530.042356     72791.711319
23  100.00       0.7   67549.732890     68885.544723
24  100.00       0.9   55399.611905     56630.312533

In [67]:
el_n_df['l1_ratio'].value_counts()

l1_ratio
0.9    100
Name: count, dtype: int64